# Change these first
owner: khrlzhfr # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: kh.rlzh.fr (Hugo/Cloudflare Pages)
    url: https://kh.rlzh.fr/?ref=upptime
    
  - name: khrlzh.fr (Hugo/Netlify)
    url: https://khrlzh.fr/?ref=upptime

status-website:
  theme: night
  cname: status.khairilzhafri.com
  logoUrl: https://kh.rlzh.fr/files/portrait.jpeg
  name: status.khairilzhafri.com
